#!/bin/bash

CONF_PATH=conf/game.conf

MAPSIZE=$1
ENEMY_NUMBER=$2

if [ -a $CONF_PATH ]; then
	rm $CONF_PATH
fi
if [ -z "$MAPSIZE" ] || [ -z "$ENEMY_NUMBER" ]; then
	echo "Please input [Map size] [Enemy number]"
	exit 1
fi
cat conf/template.conf | while IFS="" read -r LINE
do
	object_type=`echo $LINE | cut -d '{' -f2 | cut -d ',' -f1`
	echo "Object type $object_type"
	case "$object_type" in

		player)
				echo $LINE >> $CONF_PATH	
			;;
		enemy) 
			for ((n = 0; n<$ENEMY_NUMBER;n++))
			do
				POSX=$(($RANDOM%$MAPSIZE))
				POSY=$(($RANDOM%$MAPSIZE))
				new_enemy=`echo $LINE | sed 's/\*posx\*/'$POSX'/' | sed 's/\*posy\*/'$POSY'/'`
				echo $new_enemy >> $CONF_PATH
			done	
			;;
		health)
			num_health=$((100*10/$ENEMY_NUMBER))
			echo $num_health
			for ((n = 0; n<$num_health;n++))
			do
				POSX=$(($RANDOM%$MAPSIZE))
				POSY=$(($RANDOM%$MAPSIZE))
				health_cargo=`echo $LINE | sed 's/\*posx\*/'$POSX'/' | sed 's/\*posy\*/'$POSY'/'`
				echo $health_cargo >> $CONF_PATH
			done
			;;
esac
done
